from pathlib import Path
from datetime import datetime, timezone

output_dir = Path("output")
output_dir.mkdir(exist_ok=True)

file_path = output_dir / "ci-generated.txt"

file_path.write_text(
    f"Generated by GitHub Actions at {datetime.now(timezone.utc).isoformat()}\n",
    encoding="utf-8"
)

print(f"Generated {file_path}")
